GET http://localhost:5000/tests

###
POST http://localhost:5000/tests
Content-Type: application/json

{
    "test": "My Second Test"
}

###
PUT http://localhost:5000/tests/620600e211bdab41c0e36726
Content-Type: application/json

{
    "test": "New Second Test"
}

###
DELETE http://localhost:5000/tests/620600f311bdab41c0e36728
